language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  - git clone https://github.com/ruricolist/cl-murmurhash.git ~/lisp/cl-murmurhash/

script:
  - cl -l fiveam
       -e '(setf fiveam:*debug-on-error* t
                 fiveam:*debug-on-failure* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :cl-hamt-test)'

notifications:
  email:
    - shapero.daniel@gmail.com